In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
import cv2 as cv
from keras.preprocessing.image import ImageDataGenerator
%matplotlib inline

In [2]:
data=pd.read_pickle('MIR-WM811K/Python/WM811K.pkl')
data.head()

,dieSize,failureType,lotName,trainTestLabel,waferIndex,waferMap
0,1683.0,none,lot1,Training,1.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
1,1683.0,none,lot1,Training,2.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
2,1683.0,none,lot1,Training,3.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
3,1683.0,none,lot1,Training,4.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4,1683.0,none,lot1,Training,5.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."

In [4]:
data=data[:-2]
data.tail()

,dieSize,failureType,lotName,trainTestLabel,waferIndex,waferMap
811450,600.0,Edge-Loc,lot47542,Test,21.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 2,..."
811451,600.0,Edge-Loc,lot47542,Test,22.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,..."
811452,600.0,Edge-Ring,lot47542,Test,23.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1,..."
811453,600.0,Edge-Loc,lot47542,Test,24.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1,..."
811454,600.0,Edge-Ring,lot47542,Test,25.0,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1,..."

In [7]:
data.dropna(inplace=True)
data.drop(['lotName','dieSize','waferIndex'],axis=1,inplace=True)

In [17]:
data.head()

,failureType,trainTestLabel,waferMap,failureNum,trainTestNum
0,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
1,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
2,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
3,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
4,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0

In [18]:
data['failureNum']=data.failureType
data['trainTestNum']=data.trainTestLabel
mapping_type={'Center':0,'Donut':1,'Edge-Loc':2,'Edge-Ring':3,'Loc':4,'Random':5,'Scratch':6,'Near-full':7,'none':8}
mapping_traintest={'Training':0,'Test':1}
data=data.replace({'failureNum':mapping_type, 'trainTestNum':mapping_traintest})
data.head()

C:\Users\User\anaconda3\Lib\site-packages\pandas\core\array_algos\replace.py:84: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  op = lambda x: operator.eq(x, b)

,failureType,trainTestLabel,waferMap,failureNum,trainTestNum
0,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
1,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
2,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
3,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
4,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0

In [19]:


mapEncoding = pd.DataFrame({'Type': ['Center', 'Donut', 'Edge-Loc', 'Edge-Ring', 'Loc', 'Random', 'Scratch', 'Near-full', 'none'],
                           'Value':[0,1,2,3,4,5,6,7,8]})
mapEncoding.to_excel('MapEncoding.xlsx')

,failureType,trainTestLabel,waferMap,failureNum,trainTestNum
0,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
1,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
2,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
3,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0
4,none,Training,"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",8,0

In [24]:
data=data[data['failureNum'].apply(lambda x: isinstance(x, int))]

In [26]:
data.drop(['failureType','trainTestLabel'],axis=1,inplace=True)
data.head()

C:\Users\User\AppData\Local\Temp\ipykernel_4328\1918096118.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['failureType','trainTestLabel'],axis=1,inplace=True)

                                            waferMap failureNum trainTestNum
0  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
1  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
2  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
4  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0

In [43]:
data=data.reset_index()

In [53]:
dirs="images"
for index,row in mapEncoding.iterrows():
    os.makedirs(os.path.join(dirs,row[0]),exist_ok=True)

In [54]:
data.head()

                                            waferMap failureNum trainTestNum
0  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
1  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
2  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
3  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0
4  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...          8            0

In [55]:
dirs = "images"

for index, rows in data.iterrows():
    
    try:
        folder = mapEncoding.loc[mapEncoding['Value'] == rows[1]].values[0][0]
        folder_path = os.path.join(dirs, folder)
        file_path = os.path.join(folder_path, f"{folder}{index}.jpeg")

        os.makedirs(folder_path, exist_ok=True)  

        img=data['waferMap'].iloc[index]

        plt.imsave(file_path,img )
    except:
        print(index)

In [23]:
base_dir = "Images"
datagen = ImageDataGenerator(
    rotation_range=10,
                      horizontal_flip=True,
                      width_shift_range=0.2,
                      height_shift_range=0.2,
                      shear_range=0.15,
                      channel_shift_range=0.1,
                      zoom_range=0.1
)

In [22]:
dirs = 'Images'
to = 'resized1'
out_folder = os.path.join(to)
in_folder = os.path.join(dirs)

for folder in os.listdir(dirs):
    i = 0
    out_subfolder = os.path.join(out_folder, folder)
    os.makedirs(out_subfolder, exist_ok=True)

    in_subfolder = os.path.join(in_folder, folder)
    
    for image in os.listdir(in_subfolder):
        img_path = os.path.join(in_subfolder, image)

        try:
            img = plt.imread(img_path)
            #print(img_path)
            imm_path = os.path.join(out_subfolder, f"{folder}_{i}.jpeg")
            img =cv.resize(img,(224,224))
            #print(img)
            plt.imsave(imm_path, img)
            i += 1
        except Exception as e:
            print(f"Error processing {img_path}: {str(e)}")

        if i >= 20000:
            break

In [26]:
x1=os.listdir("resized1")
x1.remove('none')
print(x1)

['Center', 'Donut', 'Edge-Loc', 'Edge-Ring', 'Loc', 'Near-full', 'Random', 'Scratch']

In [30]:
dirs = 'resized1'
folder_path = 'AugmentedImages'  
os.makedirs(folder_path, exist_ok=True) 

for folder in x1:
    class_folder = os.path.join(dirs, folder)
    size = len(os.listdir(class_folder)) + 1000
    print(folder)
    for file in os.listdir(class_folder):
        file_path = os.path.join(class_folder, file)
        type_folder = os.path.join(folder_path, folder)
        os.makedirs(type_folder, exist_ok=True) 
       
        if os.path.isfile(file_path):
            img = cv.imread(file_path)
            img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
            img = np.reshape(img, (1,) + img.shape)
            
            i = 0
            for batch in datagen.flow(img, batch_size=32,
                                      save_to_dir=type_folder,
                                      save_prefix=folder,
                                      save_format='jpeg'):
                i += 1
                if i >= size // 32:  
                    break
                    
        if len(os.listdir(type_folder)) >= 10000: 
            break

print("Data augmentation completed.")

Center
Donut
Edge-Loc
Edge-Ring
Loc
Near-full
Random
Scratch
Data augmentation completed.